version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
  mcp-plex:
    build: .
    environment:
      PLEX_URL: ${PLEX_URL}
      PLEX_TOKEN: ${PLEX_TOKEN}
      TMDB_API_KEY: ${TMDB_API_KEY}
      QDRANT_URL: http://qdrant:6333
    depends_on:
      - qdrant
    command: uv run python -m mcp_plex.server --transport sse --bind 0.0.0.0 --port 8000 --mount /mcp
    ports:
      - "8000:8000"
