name: Coverage Badge (main)

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'

      - run: uv sync --no-dev
      - run: uv pip install pytest pytest-cov 'genbadge[all]'

      - name: Test w/ coverage (XML for genbadge)
        run: |
          uv run pytest \
            --cov=mcp_plex \
            --cov-report=xml \
            --cov-report=term

      - name: Make SVG badge
        run: |
          uv run genbadge coverage -i coverage.xml -o coverage.svg

      - name: Publish to orphan "coveragebadges" (single-commit branch, idempotent)
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # make sure we know about remote heads
          git fetch --prune origin

          # Prepare a clean worktree for the badge branch
          if git ls-remote --exit-code --heads origin coveragebadges >/dev/null 2>&1; then
            # Remote branch exists -> add worktree checked out to that branch
            git worktree add /tmp/coveragebadges coveragebadges || true
          else
            # No remote branch yet -> create a detached worktree and orphan the branch there
            git worktree add --detach /tmp/coveragebadges || true
            ( cd /tmp/coveragebadges && git checkout --orphan coveragebadges )
          fi

          cd /tmp/coveragebadges

          # Start from a blank tree each run
          rm -rf ./* .git/index || true

          # Drop only the badge (add more files if you must)
          cp -f "$GITHUB_WORKSPACE/coverage.svg" ./coverage.svg

          git add -A
          git commit -m "chore: update coverage badge"

          # Always replace the remote branch with this single commit
          git push -f origin HEAD:coveragebadges