name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
        with:
          python-version: '3.12'
      - run: uv sync --no-dev
      - run: uv pip install pytest ruff pytest-cov
      - run: uv run ruff check .
      - run: uv run pytest --cov=mcp_plex --cov-report=term-missing
