name: Lint and Test (PR)

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'

      - run: uv sync --no-dev
      - run: uv pip install pytest ruff pytest-cov

      - name: Ruff
        run: uv run ruff check .

      - name: Pytest + coverage
        run: |
          uv run pytest \
            --junitxml=pytest.xml \
            --cov-report=term-missing:skip-covered \
            --cov=mcp_plex tests/ | tee pytest-coverage.txt

      - name: Coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
          hide-comment: false   # yes, actually post a comment